replicaCount: 2

image:
  repository: ghcr.io/corporateguuu/ops-intelligence-api
  tag: "example"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

podAnnotations: {}

config:
  logLevel: INFO

probes:
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 20
